{{- if .Values.rbac.create -}}
{{- if .Values.k8s.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "homepage.fullname" . }}-routes-reader
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "get"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes", "gateways"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "homepage.fullname" . }}-routes-reader
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "homepage.fullname" . }}-routes-reader
subjects:
- kind: ServiceAccount
  name: {{ include "homepage.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}

